### ISSUE TITLE
NixD's sources

### ISSUE THREAD

**Issue by pinage404** [DeterminateSystems/determinate#48]
Hello,

I'm looking for NixD's sources, i don't find where they are

Where are the NixD's sources ?

**Comment by grahamc** [comment]
Hi, thank you for opening the issue. Right now, determinate-nixd is proprietary / closed source. In the future, we may open source it: general consensus on the team is that we'd like to. Before that, we'll need to establish some policies around trademarks and other legal bits. We don't have a timeline for it, though.
